config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }
  devise_for :client_users, path: "user", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' },:controllers => { :omniauth_callbacks => "user/omniauth_callbacks" } do
    get '/user/auth/:provider' => 'user/omniauth_callbacks#passthru'
  end


  devise_scope :client_user do
    
    # Landing Page will always be Client Login
    root to: "devise/sessions#new" 
    get 'policies', to: 'devise/registrations#policies'  
  end

  namespace :user, module: :user do
      
    get '/403', to: 'errors#unauthorized', as: 'unauthorized'
    get '/404', to: 'errors#notfound', as: 'notfound'
    
    get '/home', to: 'home#index', as: 'home'

    get '/free_form', to: 'free_form_widget#index', as: 'free_form'
    post '/translate', to: 'free_form_widget#translate', as: 'translate'
    post '/export_free_translation', to: 'free_form_widget#export_free_translation', as: 'export_free_translation'

    get '/translation_request', to: 'free_form_widget#new_translation_request', as: 'new_translation_request'
    post '/translation_request', to: 'free_form_widget#create_translation_request', as: 'create_translation_request'
    # Upload ingredient through CSV file (CSV file Upload and parsing)
    get '/csv_upload', to: 'table_documents#csv_upload', as: 'csv_upload'
      # Parse CSV data
    post 'csv_parse', to: 'table_documents#csv_parse', as: 'csv_parse'
    
    root to: 'home#index'
    # root to: 'user_subscriptions#index'  #Redirect to susbscription page after login or registration

    #for payment
    resources :charges, only: [:index, :new, :create]

    
    # Listing All Kinds of Documents
    resources :documents, only: [:index, :destroy] do
      # Update the status of the document
      member do
        put :update_status
        put :drag_drop
      end
    end

    # CRUD Template Documents
    resources :template_documents do
      member do

         put 'update_template_folder', to: 'template_documents#update_folder' 
        # Create or Update the Document and Translate
        
        put 'save_and_translate', to: 'template_documents#save_and_translate', as: 'save_and_translate'

        get 'preview', to: 'template_documents#preview', as: 'preview'

        # Print the Document in the PDF format
        get 'print', to: 'template_documents#print', as: 'print'

        #update status
        put 'update_status', to: 'template_documents#update_status', as: 'update_status'
        get '/export_template_documents_translation', to: 'template_documents#export_template_documents_translation', as: 'export_template_documents_translation'


      end

      collection do
        get 'select_template', to: 'template_documents#select_template', as: 'select_template'
      end
    end
    resources :client_feedbacks do

      collection do

       post 'new', to: 'client_feedbacks#new', as: 'new'

      end  
    end  


    # CRUD Table Documents
    resources :table_documents do

      collection do
        # Save Methods
        put 'save_everything', to: 'table_documents#save_everything', as: 'save_everything'
        put 'translate_input_phrase', to: 'table_documents#translate_input_phrase', as: 'translate_input_phrase'
        
      end

      member do
        # Export to Excel
        get 'export_to_excel', to: 'table_documents#export_to_excel', as: 'export_to_excel'
        get 'clear', to: 'table_documents#clear', as: 'clear'

        #update status
        put 'update_status', to: 'table_documents#update_status', as: 'update_status'
        #update folder
        put 'update_table_folder', to: 'table_documents#update_folder' 
      end
    end
   
    # Update  Profile
    get 'edit_client_profile', to: 'client_profile#edit'
    put 'update_client_profile', to: 'client_profile#update'
    put 'update_client_password', to: 'client_profile#update_password'
    get 'zoho_call_back', to: 'user_subscriptions#zoho_call_back', as: 'zoho_call_back'
    resources :user_subscriptions
    resources :user_subscriptions, only: [:create, :index, :update] do
     collection do
      put :update
      post :subscribe 
      post :downgrade_subscription 
      end
    end
    
    #Crud Folder
      resources :document_folder
      put 'update_document', to: 'document_folder#update_document'
  end
  
  devise_for :admin_users, path: "admin", skip: [:registrations], path_names: { sign_in: 'login', sign_out: 'logout', edit: 'settings' }

  namespace :admin, module: :admin do

    # Admin Home
    get '/home', to: 'home#index', as: 'home'

    # FIXME - not sure why we need this
    root to: 'home#index'
    
    # Client Feedbacks
    resources :client_feedbacks, only: [:index]
    
    # Translation Requests
    resources :translation_requests, only: [:index, :create, :show]

    # CRUD Client Users
    resources :client_users

    # CRUD Admin Users
    resources :admin_users    
    
    # CRUD Translations
    resources :translations

    # Upload Translations Database 
    resources :upload_translations, only: [:index, :create]

    resources :translation_query_histories, only: [:index]

    # CRUD Label Templates
    resources :label_templates
    
    resources :translation_uploads_history, only: [:index, :show]
    # CRUD Nutrition Fact Templates
    # resources :nutrition_fact_templates
    
    # Update Admin Profile
    get 'edit_profile', to: 'profile#edit'
    put 'update_profile', to: 'profile#update'
    put 'update_password', to: 'profile#update_password'
    
    #User Module Subscription
    resources :subscription_permissions , only: [:create, :index, :update] do
      collection do
        get '/add_edit_permissions/:id', to: 'subscription_permissions#create_pemission'
        
      end
    end
    
    
  
  end
  
  namespace :api, module: :api do
        post 'downgrading_api', to: 'user_subscriptions#downgrading_api', as: 'downgrading_api'
        post 'test_api', to: 'user_subscriptions#test_api', as: 'test_api'
        get 'test_api', to: 'user_subscriptions#test_api_2', as: 'test_api2'
        get 'zoho_test', to: 'user_subscriptions#zoho_test', as: 'zoho_test'
        post 'zoho_test', to: 'user_subscriptions#zoho_test2', as: 'zoho_test2'
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < Admin::BaseController

    before_action :authenticate_admin_user!

    def index

      @page_title = "Home | Admin"
      @nav = "admin/home"
      
    end

    def free_form

      @page_title = "Free Form | Admin"
      @nav = "admin/free_form"
      
    end
    
    private

    
    
  end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  
  layout 'login'
  
  def index
    @page_title = "Home | User"
    @nav = 'user/home'
  end

end

app/controllers/user/home_controller.rb
module User
  class HomeController < User::BaseController

    before_action :authenticate_client_user!
    skip_before_action :verify_authenticity_token
    before_action :get_languages
    before_action :access_denied
    before_action :check_subscription_plan, only: [:index]

    def index
      @page_title = "Home | User"
      @nav = 'user/home'
    end

    private

    def get_languages
      @input_language = params[:input_language].to_s.strip unless params[:input_language].to_s.strip.blank?
      @output_language = params[:output_language].to_s.strip unless params[:output_language].to_s.strip.blank?

      @input_language = "ENGLISH" unless @input_language
      @output_language = "ARABIC" unless @output_language
    end

    def check_subscription_plan
      # binding.pry
      user_subscription = ZohoSubData.find_by('client_user_id=?',current_client_user)
      # user_subscription = UserSubscription.find_by(user_id:current_client_user)
      @trial_period = (Date.today.to_date - current_client_user.created_at.to_date).to_i

      if user_subscription.subscription.title.downcase == "Free".downcase && @trial_period >= 7
        redirect_to controller: :user_subscriptions, action: :index
      end

    end


  end
end

app/views/user/home/widgets/_new_document.html.erb
<div class="row clearfix its-upload-container its-home-secondary-box">
  <!-- Block 01 -->
  <div class="col-lg-4 col-md-4">
    <div class="card">
      <div class="body">
        <div class="d-flex align-items-center">
              <div class="icon-in-bg bg-azura text-white rounded-circle">                      
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 71.4 55.7" width="30" height="30"><defs><style>.cls-1{fill:#026649;}</style></defs><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M24.8,4.4l5.4,5.4,1.4,1.3H66.9V51.2H4.5V4.4Zm2-4.4H4.5A4.22,4.22,0,0,0,1.3,1.3,4.22,4.22,0,0,0,0,4.5V51.2a4.22,4.22,0,0,0,1.3,3.2,4.22,4.22,0,0,0,3.2,1.3H66.9a4.44,4.44,0,0,0,4.5-4.5V11.1a4.22,4.22,0,0,0-1.3-3.2,4.22,4.22,0,0,0-3.2-1.3H33.5Z"/></g></g></svg>
              </div>
          <div class="ml-4 its-upload-title">
            <h3>Browse Templates</h3>
          </div>
        </div>
        <div class="mt-4">
          <div class="its-home-min-height">
            <p>Choose from a selection of available templates for instant and print-ready translated labels. New templates are added all the time so please check frequently or contact us regarding any specific requirements. </p>
          </div>
          <button class="btn btn-primary btn-block" type="button">
            <%= link_to "Select a Template", select_template_user_template_documents_path, style: "color: #fff;display: block;" %>
          </button>
        </div>
      </div>
    </div>
  </div>
  <!-- Block 02 -->
  <div class="col-lg-4 col-md-4">
    <div class="card">
      <div class="body">
        <div class="d-flex align-items-center">
              <div class="icon-in-bg bg-azura text-white rounded-circle">                      
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 53.9 64.7" width="30" height="30"><defs><style>.cls-1{fill:#026649;}</style></defs><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M34.8,0H3.8A3.69,3.69,0,0,0,1.1,1.1,3.69,3.69,0,0,0,0,3.8V60.9a3.69,3.69,0,0,0,1.1,2.7,3.69,3.69,0,0,0,2.7,1.1H50.1a3.76,3.76,0,0,0,3.8-3.8V19ZM32.9,3.8h.4L50.1,20.7V21H32.9V3.8ZM50.1,44.4v6.4H3.8V44.4ZM3.8,40.5V34.2H50.1v6.3Zm0-10.2V23.9H29.1v.9h21v5.5ZM29.1,20.2H3.8V13.8H29.1Zm0-16.4V10H3.8V3.8ZM3.8,61V54.6H50.1V61Z"/></g></g></svg>
              </div>
            <div class="ml-4 its-upload-title">
              <h3>Sheet Translation</h3>
            </div>
        </div>
        <div class="mt-4">
          <div class="its-home-min-height">
            <p>Use this option for an ingredient-by-ingredient translation. Fill in the relevant fields and choose your preferred output template. Supports group copy/pasting from Microsoft Excel. </p>
          </div>
          <button class="btn btn-primary btn-block" type="button">
            <%= link_to "Try it Out", new_user_table_document_path(), style: "color: #fff;display: block;" %>
          </button>
        </div>
      </div>
    </div>
  </div>
  <!-- Block 03 -->
  <div class="col-lg-4 col-md-4">
    <div class="card">
      <div class="body">
        <div class="d-flex align-items-center">
             <div class="icon-in-bg bg-azura text-white rounded-circle">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 68.6 65" width="30" height="30"><defs><style>.cls-1{fill:#026649;}</style></defs><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M61.7,60.6H4.4V16.5H22.1l4.5-4.3-.1-.1H4.4a4,4,0,0,0-3.1,1.3A4.57,4.57,0,0,0,0,16.5V60.6a4,4,0,0,0,.6,2.2,4.89,4.89,0,0,0,1.6,1.6,4.28,4.28,0,0,0,2.2.6H61.7a4.16,4.16,0,0,0,3.1-1.3,4,4,0,0,0,1.3-3.1V26.1l-4.4,4.2ZM68.6,0H64.1a37.3,37.3,0,0,1-6.7,15.7A37,37,0,0,1,44.3,26.8a36.67,36.67,0,0,1-16.9,4.1c-.4,0-1.2,0-2.3-.1l8.1-8.1c.1-.1.3-.3.3-.4s.2-.3.2-.5.1-.4.1-.6a1.27,1.27,0,0,0-.1-.6c0-.2-.1-.3-.2-.5s-.2-.3-.3-.5a1.79,1.79,0,0,0-.7-.5,2.77,2.77,0,0,0-.9-.1,1.27,1.27,0,0,0-.6.1.76.76,0,0,0-.5.2c-.1.1-.3.2-.4.3L17.1,33l13,13.4a2.11,2.11,0,0,0,1.6.6,2.45,2.45,0,0,0,1.6-.6,2.07,2.07,0,0,0,.6-1,2,2,0,0,0,0-1.1,2.07,2.07,0,0,0-.6-1l-8-8h2.1a41.28,41.28,0,0,0,19.2-4.7A41,41,0,0,0,61.3,17.9,44.08,44.08,0,0,0,68.6,0Z"/></g></g></svg>
              </div>
              <div class="ml-4 its-upload-title">
                <h3>Import</h3>
              </div>
        </div>
        
        <div class="mt-4">
          <div class="its-home-min-height">
            <p>Use this option to upload compatible ingredients files and export the translation in one of many supported formats including Microsoft Excel and Adobe PDF.</p>
          </div>
          <button class="btn btn-primary btn-block" type="button">
            <%= link_to "Upload", user_csv_upload_url, style: "color: #fff;display: block;", remote: true %>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/home/widgets/_recent_translations.html.erb
<%
  @documents = @current_client_user.documents.activated.limit(5).order("created_at DESC").all
%>

<div class="col-lg-12 col-md-12">
  <div class="header">
    <h2>Recent Translations</h2>
  </div>
  
  <% if @documents.any? %>
  
    <!-- Rendering the Table -->
    <%= render partial: 'user/documents/index/table', locals: {display_actions: false} %>

  <% else %>

    <a class="card">
      <div class="body text-center">
        <h6 class="mt-3">You haven't started yet</h6>
        <div class="text-center text-muted">Click on a button above. Its easy.</div>
      </div>
    </a>

  <% end %>

</div>

app/views/user/home/widgets/_try_translation.html.erb
<div class="row clearfix its-upload-container">
  <div class="col-lg-12 col-md-12">
    <div class="card">
      <div class="body" style="background: #f9fdf9;border: 1px solid gainsboro;">
        <div class="mt-2">

          <div class="row its-language-switcer mb-2">

            <div class="col-md-12">
              <div class="mb-4 text-center">
                <h3>Freeform Ingredient Translation</h3>
                <p>Please separate ingredients using <span class='badge badge-info'>,</span> or <span class='badge badge-info'>;</span> or new lines for accurate results. <br>Kindly note this is a specialist tool for translating ingredient names and will not process natural language.</p>
              </div>
            </div>

            <div class="col-md-6">
              <div class="row">
                <h4 class="col-md-6">Input Language</h4>
                <div class="col-md-6">
                  <select class="form-control form-control-xs selectpicker1" name="" data-size="7" data-live-search="true" data-title="Location" id="INPUT_LANGUAGE" data-width="100%">
                    <option value="ENGLISH" <%= @input_language == "ENGLISH" ? "selected" : "" %> >English</option>
                    <option value="ARABIC" <%= @input_language == "ARABIC" ? "selected" : "" %> >Arabic</option>
                    <option value="FRENCH" <%= @input_language == "FRENCH" ? "selected" : "" %> >French</option>
                  </select>
                </div>
              </div>
            </div>

            <div class="col-md-6">
              <div class="row">
                <div class="col-md-6">
                  <select class="form-control form-control-xs selectpicker1" name="" data-size="7" data-live-search="true" data-title="Location" id="OUTPUT_LANGUAGE" data-width="100%">
                    <option value="ENGLISH" <%= @output_language == "ENGLISH" ? "selected" : "" %> >English</option>
                    <option value="ARABIC" <%= @output_language == "ARABIC" ? "selected" : "" %> >Arabic</option>
                    <option value="FRENCH" <%= @output_language == "FRENCH" ? "selected" : "" %> >French</option>
                  </select>
                </div>
                <h4 class="col-md-6" style="text-align: right;">Output Language</h4>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="playground-wrapper">
                <% 
                  case @input_language
                  when "FRENCH"
                    enter_text = "Entrer"
                    sg_dir = "dir-ltr"
                  when "ARABIC"
                    enter_text = "أدخل"
                    sg_dir = "dir-rtl"
                  when "ENGLISH"
                    enter_text = "Enter"
                    sg_dir = "dir-ltr"
                  end
                %>
                <textarea id="TRANS_PLAYGROUND" placeholder="<%= enter_text %>"></textarea>
                <div id="WORD_SUGGESTIONS">
                  <div class="sg-container" id="" style="user-select: none;">
                    <div class="sg-holder" id="" role="menuitem" style="user-select: none;">
                      <div class="sg-word <%= sg_dir %>" id="">Apple</div>
                      <span></span>
                    </div>
                    <div class="sg-holder" id=":6" role="menuitem" style="user-select: none;">
                      <div class="sg-word <%= sg_dir %>" id="">Mango</div>
                      <span></span>
                    </div>
                    <div class="sg-holder" id=":6" role="menuitem" style="user-select: none;">
                      <div class="sg-word <%= sg_dir %>" id="">Grapes</div>
                      <span></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <% styles = @output_language.upcase == "ARABIC" ? "text-align:right;" : "text-align:left;" %>
              <div style="<%= styles %>" id="TRANS_PREVIEW" dir="rtl"></div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<%# Need to integrate tribute.js and load translations from server %>
<%= content_for :javascript_footer do %>
  
  if(typeof(String.prototype.trim) === "undefined")
  {
    String.prototype.trim = function() 
    {
      return String(this).replace(/^\s+|\s+$/g, '');
    };
  }

  function ITSTranslate() {
    let inputLanguage = $("#INPUT_LANGUAGE").children("option:selected").text();
    let outputLanguage = $("#OUTPUT_LANGUAGE").children("option:selected").text();
    let inputText = $("#TRANS_PLAYGROUND").val();
    let ajaxData = {text: inputText, input_language: inputLanguage, output_language: outputLanguage };
    $.ajax({
      url: '/user/try.js',
      type: 'POST',
      data: ajaxData
    });
  }

  $(document).off('change', "#TRANS_PLAYGROUND");
  $(document).on('change', '#TRANS_PLAYGROUND', function (e) {
    ITSTranslate()
  });

  $(document).off('input', "#TRANS_PLAYGROUND");
  $(document).on('input', '#TRANS_PLAYGROUND', function (e) {
    let inputText = $("#TRANS_PLAYGROUND").val();
    
    if(/(\s+|\d+|\.|,|;|\(|\)|\[|\]|:|\t+|\n+|\r+)$/.test(inputText)) {
      ITSTranslate();
    }
  });

  $("#INPUT_LANGUAGE").on('change', function(){
    ITSTranslate();
  });
  
  $("#OUTPUT_LANGUAGE").on('change', function(){
    ITSTranslate()
  });

<% end %>

<style type="text/css">
  #TRANS_PLAYGROUND {
    width: 100%;
    height: auto;
    min-height: 200px;
    font-size: 20px;
    padding: 20px;
    border: 0;
    outline: none;
    resize: none;
  }

  #TRANS_PREVIEW {
    width: 100%;
    height: 300px;
    font-size: 20px;
    padding: 40px;
    border: 1px solid #c1c1c1;
    background-color: #fff;
    color: #4b4b4b;
    outline: none;
    resize: none;
    overflow: auto;
  }

  #WORD_SUGGESTIONS {
    display: none;
  }

  .playground-wrapper {
    width: 100%;
    height: 300px;
    border: 1px solid #c1c1c1;
    padding: 20px;
    font-size: 20px;
    background-color: #fff;
    color: #4b4b4b;
  }

  .playground-wrapper > .contenteditable {
    border: none;
    outline: none;
  }

  .sg-container {
    list-style-type: none;
    margin-top:20px;
    padding-top: 20px;
  }
  .sg-holder {
    background: #F5F5F5;
    border-radius: 14px;
    box-sizing: border-box;
    color: #6B6B6B;
    cursor: pointer;
    display: inline-block;
    direction: inherit;
    font-family: 'Roboto',sans-serif;
    font-size: 13px;
    height: 28px;
    line-height: 28px;
    margin-right: 4px;
    padding: 0 10px;
    position: relative;
    margin-bottom: 4px;
    max-width: 100%;
    overflow: hidden;
    text-overflow: ellipsis;
    vertical-align: top;
    white-space: nowrap;
  }
  .sg-item {
    color: rgba(0,0,0,.87);
    display: inline-block;
    font-size: 12px;
    position: relative;
  }
  .dir-rtl {
    direction: rtl;
  }
  .dir-ltr {
    direction: ltr;
  }
  .not-found {
    color: red;
    text-decoration: underline;
  }

</style>