config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }
  devise_for :client_users, path: "user", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' },:controllers => { :omniauth_callbacks => "user/omniauth_callbacks" } do
    get '/user/auth/:provider' => 'user/omniauth_callbacks#passthru'
  end


  devise_scope :client_user do
    
    # Landing Page will always be Client Login
    root to: "devise/sessions#new" 
    get 'policies', to: 'devise/registrations#policies'  
  end

  namespace :user, module: :user do
      
    get '/403', to: 'errors#unauthorized', as: 'unauthorized'
    get '/404', to: 'errors#notfound', as: 'notfound'
    
    get '/home', to: 'home#index', as: 'home'

    get '/free_form', to: 'free_form_widget#index', as: 'free_form'
    post '/translate', to: 'free_form_widget#translate', as: 'translate'
    post '/export_free_translation', to: 'free_form_widget#export_free_translation', as: 'export_free_translation'

    get '/translation_request', to: 'free_form_widget#new_translation_request', as: 'new_translation_request'
    post '/translation_request', to: 'free_form_widget#create_translation_request', as: 'create_translation_request'
    # Upload ingredient through CSV file (CSV file Upload and parsing)
    get '/csv_upload', to: 'table_documents#csv_upload', as: 'csv_upload'
      # Parse CSV data
    post 'csv_parse', to: 'table_documents#csv_parse', as: 'csv_parse'
    
    root to: 'home#index'
    # root to: 'user_subscriptions#index'  #Redirect to susbscription page after login or registration

    #for payment
    resources :charges, only: [:index, :new, :create]

    
    # Listing All Kinds of Documents
    resources :documents, only: [:index, :destroy] do
      # Update the status of the document
      member do
        put :update_status
        put :drag_drop
      end
    end

    # CRUD Template Documents
    resources :template_documents do
      member do

         put 'update_template_folder', to: 'template_documents#update_folder' 
        # Create or Update the Document and Translate
        
        put 'save_and_translate', to: 'template_documents#save_and_translate', as: 'save_and_translate'

        get 'preview', to: 'template_documents#preview', as: 'preview'

        # Print the Document in the PDF format
        get 'print', to: 'template_documents#print', as: 'print'

        #update status
        put 'update_status', to: 'template_documents#update_status', as: 'update_status'
        get '/export_template_documents_translation', to: 'template_documents#export_template_documents_translation', as: 'export_template_documents_translation'


      end

      collection do
        get 'select_template', to: 'template_documents#select_template', as: 'select_template'
      end
    end
    resources :client_feedbacks do

      collection do

       post 'new', to: 'client_feedbacks#new', as: 'new'

      end  
    end  


    # CRUD Table Documents
    resources :table_documents do

      collection do
        # Save Methods
        put 'save_everything', to: 'table_documents#save_everything', as: 'save_everything'
        put 'translate_input_phrase', to: 'table_documents#translate_input_phrase', as: 'translate_input_phrase'
        
      end

      member do
        # Export to Excel
        get 'export_to_excel', to: 'table_documents#export_to_excel', as: 'export_to_excel'
        get 'clear', to: 'table_documents#clear', as: 'clear'

        #update status
        put 'update_status', to: 'table_documents#update_status', as: 'update_status'
        #update folder
        put 'update_table_folder', to: 'table_documents#update_folder' 
      end
    end
   
    # Update  Profile
    get 'edit_client_profile', to: 'client_profile#edit'
    put 'update_client_profile', to: 'client_profile#update'
    put 'update_client_password', to: 'client_profile#update_password'
    get 'zoho_call_back', to: 'user_subscriptions#zoho_call_back', as: 'zoho_call_back'
    resources :user_subscriptions
    resources :user_subscriptions, only: [:create, :index, :update] do
     collection do
      put :update
      post :subscribe 
      post :downgrade_subscription 
      end
    end
    
    #Crud Folder
      resources :document_folder
      put 'update_document', to: 'document_folder#update_document'
  end
  
  devise_for :admin_users, path: "admin", skip: [:registrations], path_names: { sign_in: 'login', sign_out: 'logout', edit: 'settings' }

  namespace :admin, module: :admin do

    # Admin Home
    get '/home', to: 'home#index', as: 'home'

    # FIXME - not sure why we need this
    root to: 'home#index'
    
    # Client Feedbacks
    resources :client_feedbacks, only: [:index]
    
    # Translation Requests
    resources :translation_requests, only: [:index, :create, :show]

    # CRUD Client Users
    resources :client_users

    # CRUD Admin Users
    resources :admin_users    
    
    # CRUD Translations
    resources :translations

    # Upload Translations Database 
    resources :upload_translations, only: [:index, :create]

    resources :translation_query_histories, only: [:index]

    # CRUD Label Templates
    resources :label_templates
    
    resources :translation_uploads_history, only: [:index, :show]
    # CRUD Nutrition Fact Templates
    # resources :nutrition_fact_templates
    
    # Update Admin Profile
    get 'edit_profile', to: 'profile#edit'
    put 'update_profile', to: 'profile#update'
    put 'update_password', to: 'profile#update_password'
    
    #User Module Subscription
    resources :subscription_permissions , only: [:create, :index, :update] do
      collection do
        get '/add_edit_permissions/:id', to: 'subscription_permissions#create_pemission'
        
      end
    end
    
    
  
  end
  
  namespace :api, module: :api do
        post 'downgrading_api', to: 'user_subscriptions#downgrading_api', as: 'downgrading_api'
        post 'test_api', to: 'user_subscriptions#test_api', as: 'test_api'
        get 'test_api', to: 'user_subscriptions#test_api_2', as: 'test_api2'
        get 'zoho_test', to: 'user_subscriptions#zoho_test', as: 'zoho_test'
        post 'zoho_test', to: 'user_subscriptions#zoho_test2', as: 'zoho_test2'
  end
end

app/views/user_mailer_notification/notification.html.erb
    <!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="bar1"></div>
        <div class="bar2"></div>
        <div class="bar3"></div>
        <div class="bar4"></div>
        <div class="bar5"></div>
    </div>
</div>

<div class="auth-main2">
  <div class="vivify its-login-container">
    <div class="container">
      <div class="row">
        <div class="col-md-12" style="display: none;">
          <div class="auth_brand m-t-60" style="text-align: center;">
            <a class="navbar-brand" href="javascript:void(0);">
              <!-- <img src="../assets/images/itsme-logo-1.png" width="142" height="60" class="d-inline-block" alt=""> -->
              <%= image_tag "itsme-logo-1.png", alt: "Login Image", class: "d-inline-block", width: "142", height: "60" %>
            </a>
          </div>
          
        </div>
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-10" style="margin: 0 auto">
              <div class="card m-t-20">
                <div class="body its-login-body">
                  <div class="row">
                    <div class="col-md-6 its-login-bg">
                        <div style="width: 100%;height: 100%;display: table;">
                            <div style="width: 100%;height: 100%;display: table-cell;vertical-align: middle;">

                              <%= image_tag "keyart-2.png", alt: "Login Image", style: "max-width: 80%;" %>

                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 its-login-form">
                      <div class="row its-login-header">
                        <!-- Mobile Logo -->
                        <div class="col-md-4 hide-desk show-tab">
                          <div class="auth_brand"> <a class="navbar-brand" href="javascript:void(0);">
                            <%= image_tag "itsme-logo-1.png", alt: "Login Image", class: "d-inline-block" %>
                          </a> </div>
                        </div>

                        <div class="col-md-8">
                          <div class="mb-3">
                            <p class="lead"></p>
                          </div>
                        </div>
                        <div class="col-md-4 hide-mob hide-tab">
                          <div class="auth_brand">
                            <a class="navbar-brand" href="javascript:void(0);">
<!--                               <img src="../assets/images/itsme-logo-1.png" class="d-inline-block" alt="">
 -->                              <%= image_tag "itsme-logo-1.png", alt: "Login Image",  									 class: "d-inline-block" %>
                            </a>
                          </div>
                        </div>


                      </div>



                      
                          <div class="mb-3">
                              <p>Please verify your email to reset password. </p>
                          </div>
                            <div class="mb-3">  
                          </div>
                          <div class="form-group">
                            <div class="input-group">
                              
                            </div>
                          </div>
                         


                      <div class="bottom">
                        <span class="helper-text"><%= link_to "Back to Home", new_client_user_session_path %></span>
                      </div>
                      
                    </div>
                  </div>
                </div>
              </div>
              
            </div>
            
          </div>
          
        </div>
        
      </div>
      
    </div>
  </div>
</div>

app/views/user_mailer_notification/send_forgot_password.html.erb
<center>
	<img class="d-inline-block" src="https://app.itslabel.me/assets/itsme-logo-1-a1c066cb066e5e7d069f1b5b16055121a0702106fe006d0212d213bf904ac2f9.png" height="200" width="500" align="middle">
	<br>
	<h2>Reset Your Password Here!</h2>
	<p>Seems like you forgot your password for ITS, If this is true click below to reset your password</p>
	<a href="http://localhost:3000/users/password/edit?t=<%=@password_token%>,s=<%=@password_sent_at%>">Click Here</a>
	<p>if you did not forgot your password you can safely ignore this email.</p>
	<hr>
	<p>© ITS. 1801 California St., Suite 500, Denver, CO 80202 USA</p>
</center> 

app/views/user_mailer_notification/send_welcome_email.html.erb
<img align="center" alt="" src="https://ci5.googleusercontent.com/proxy/vD4UDIF7WcyysbDGkUBsH7FM4CpecBCDJ7kvVD9jytnRqwWmDgYaokmg1HWDl4ghNTGsQ4d7_pdIcBYewHHpDZ4QzcKg_DCK3S0G8Ubgg-TyGp9CHHMWPuOXuVD11WPi56873-MHg9EAv3dZwY_z_qfZDuNOVQ=s0-d-e1-ft#https://mcusercontent.com/893355588917bd831ad08eddd/images/c2d65d0e-7cc3-4c2b-b955-7e957c993ba6.png" width="395" style="max-width:395px;padding-left: 280px;padding-bottom:0;display:inline!important;vertical-align:bottom;right:60px;" class="m_mcnImage">
<div style="padding:0px 15px">Dear <%=@client_user.display_name%>,<br>
	<br>
	Thank you for signing up for <strong>ITSLabel.me</strong> - <strong style="color:#00674a;font-weight:bold;text-decoration:none">Food Ingredients Translation platform.</strong><br>
	<br>
	We designed <strong>ITSLabel.me</strong> to be a very useful and cost-effective tool to support your export and translation requirements and believe you and your team will find it tremendously helpful whether you manage localisations internally or through a third-party supplier.<br>
	<br>
	<strong style="color:#00674a;font-weight:bold;text-decoration:none">ITSLabel.me supports¦</strong><br>

	<ul>
		<li><strong style="color:#00674a;font-weight:bold;text-decoration:none">The localisation of a proprietary database of over 6,000 ingredients from and to 4 languages: Arabic, English, French, and Spanish.</strong></li>
		<li><strong style="color:#00674a;font-weight:bold;text-decoration:none">Complex Chemicals</strong></li>
		<li><strong style="color:#00674a;font-weight:bold;text-decoration:none">E-Numbers</strong></li>
		<li><strong style="color:#00674a;font-weight:bold;text-decoration:none">Measurement Units</strong></li>
	</ul>

	Our roadmap is filled with exciting new features that will be deployed in due course, along with additional languages, so please try it out and give us your feedback.<br>
	<br>
	<strong style="color:#00674a;font-weight:bold;text-decoration:none">Thank you once again and we look forward to supporting your business.</strong><br><br>
</div>
<a href="https://itslabel.me" title="" target="_blank" rel="noreferrer">
<img align="center" alt="" src="https://ci5.googleusercontent.com/proxy/PaDB3KXnP9Pmw5GaozWJlP5Zerytbhsl4nmG0NmHfQXSrHQAP5JSx1C5IMR-fumaPrszuPCRXZnbsHM9vPdnN678dIX6ccdN-hHKeoraA8qSbXKeqWPWeVoFMr6_yoO124PFpoK9zMaDuX9O6iYQSWh0ZoWHXg=s0-d-e1-ft#https://mcusercontent.com/893355588917bd831ad08eddd/images/d820324e-11e4-4a92-83f6-d558ea407af2.jpg" width="395" style="max-width:395px;padding-left: 280px;padding-bottom:0;display:inline!important;vertical-align:bottom" class="m_mcnImage">
</a>